import type { MachineContext } from '$lib/domain/types';

/**
 * The plant's assets, keyed by the ID printed on the nameplate.
 *
 * HOW THE DEVICE KNOWS WHICH MACHINE IT IS LOOKING AT
 * The QR code stuck to the machine encodes a URL carrying the asset ID:
 * `https://…/?asset=AST-3121`. That is the entire mechanism, and it is what
 * makes doinstruct's "no app, no login, no barriers" actually work. The thing
 * being identified is the machine, not the person, so there is nothing to log
 * in to and nothing to remember.
 *
 * An asset ID is not a secret. It is painted on the machine, printed in the
 * manual and readable by anyone standing in front of it, so putting it in a URL
 * gives away nothing that the nameplate does not.
 *
 * WHAT A STICKER CANNOT KNOW
 * A sticker is static, so it cannot carry today's fault code. The first version
 * of this prototype showed one anyway, which quietly claimed a live integration
 * that does not exist. The fault code is now only present when the URL carries
 * it, which models the second entry path: a deep link generated by a system that
 * does know the line's current state, such as an HMI or a maintenance ticket.
 *
 * Plain sticker:  ?asset=AST-3121
 * Deep link:      ?asset=AST-3121&fault=E-212
 *
 * AGENTS: asset IDs, machine names and line names are identifiers and are never
 * localised, in any language. A worker has to match them against a nameplate.
 */
export const ASSETS: Record<string, Omit<MachineContext, 'faultCode'>> = {
	'AST-3121': { line: 'Linie 3, Abfüllung', machine: 'Füller F2', assetId: 'AST-3121' },
	'AST-2210': { line: 'Linie 3, Abfüllung', machine: 'Palettierer P1', assetId: 'AST-2210' },
	'AST-0030': { line: 'Linie 3, Abfüllung', machine: 'CIP-Station', assetId: 'AST-0030' },
	'AST-1180': { line: 'Linie 2, Etikettierung', machine: 'Etikettierer E4', assetId: 'AST-1180' },
	'AST-1204': { line: 'Linie 2, Etikettierung', machine: 'Übergabe Ü2', assetId: 'AST-1204' }
};

/**
 * What the reviewer sees at the bare URL, with no QR code involved.
 *
 * A real deployment has no default: you arrive by scanning something. This one
 * exists so the prototype opens on a screen rather than on an error, and it is
 * named `DEMO_ASSET` rather than `DEFAULT_ASSET` so nobody mistakes it for
 * product behaviour.
 */
export const DEMO_ASSET = 'AST-3121';

/**
 * Resolve the machine from the URL a QR code produced.
 *
 * Returns `null` for an asset that is not in the plant's register, which is a
 * real case: stickers outlive machines, get moved, and get printed wrong. The
 * caller decides what to show, and the answer is not a dead end. See
 * `+page.svelte`.
 */
export function resolveAsset(url: URL): MachineContext | null {
	const id = url.searchParams.get('asset') ?? DEMO_ASSET;
	const asset = ASSETS[id];
	if (!asset) return null;

	const fault = url.searchParams.get('fault');
	return fault ? { ...asset, faultCode: fault } : { ...asset };
}
